default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: papatest_development
test:
  <<: *default
  database: papatest_test
  max_requests_per_second: 50

production:
  <<: *default
  database: papatest_production
  username: deploy
  password: Rails.application.credentials.dig(:production, :db_password)
